name: ERC
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohappyeyeballs=2.4.0=py38h06a4308_0
  - aiohttp=3.10.5=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.14=h5eee18b_0
  - amply=0.1.6=py38h06a4308_0
  - anndata=0.9.2=pyhd8ed1ab_0
  - annotated-types=0.6.0=py38h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.2.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bbmap=39.33=he5f24ec_0
  - bcrypt=3.2.0=py38h5eee18b_1
  - bedtools=2.31.1=h13024bc_3
  - binutils_impl_linux-64=2.40=h5293946_0
  - bioconductor-biobase=2.66.0=r44h3df3fcb_0
  - bioconductor-biocgenerics=0.52.0=r44hdfd78af_0
  - bioconductor-biocio=1.16.0=r44hdfd78af_0
  - bioconductor-biocparallel=1.40.0=r44he5774e6_0
  - bioconductor-biostrings=2.74.0=r44h3df3fcb_1
  - bioconductor-bsgenome=1.74.0=r44hdfd78af_0
  - bioconductor-data-packages=20250105.1=hdfd78af_0
  - bioconductor-delayedarray=0.32.0=r44h3df3fcb_0
  - bioconductor-dnacopy=1.80.0=r44h4d5c4aa_0
  - bioconductor-edger=4.4.0=r44h3df3fcb_0
  - bioconductor-genomeinfodb=1.42.0=r44hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.13=r44hdfd78af_0
  - bioconductor-genomicalignments=1.42.0=r44h3df3fcb_0
  - bioconductor-genomicranges=1.58.0=r44h3df3fcb_0
  - bioconductor-iranges=2.40.0=r44h3df3fcb_1
  - bioconductor-limma=3.62.1=r44h15a9599_0
  - bioconductor-matrixgenerics=1.18.0=r44hdfd78af_0
  - bioconductor-repitools=1.52.0=r44he5774e6_0
  - bioconductor-rhtslib=3.2.0=r44h15a9599_1
  - bioconductor-rsamtools=2.22.0=r44h77050f0_0
  - bioconductor-rtracklayer=1.66.0=r44h15a9599_0
  - bioconductor-s4arrays=1.6.0=r44h3df3fcb_0
  - bioconductor-s4vectors=0.44.0=r44h3df3fcb_1
  - bioconductor-sparsearray=1.6.0=r44h3df3fcb_0
  - bioconductor-summarizedexperiment=1.36.0=r44hdfd78af_0
  - bioconductor-ucsc.utils=1.2.0=r44hdfd78af_0
  - bioconductor-xvector=0.46.0=r44h15a9599_1
  - bioconductor-zlibbioc=1.52.0=r44h3df3fcb_1
  - biopython=1.83=py38h01eb140_0
  - bismark=0.24.2=hdfd78af_0
  - blas=1.0=mkl
  - boto3=1.34.154=py38h06a4308_0
  - botocore=1.34.154=py38h06a4308_0
  - bottleneck=1.3.7=py38ha9d4c09_0
  - bowtie2=2.5.4=he96a11b_5
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py38h6a678d5_8
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=py_0
  - cachetools=5.3.3=py38h06a4308_0
  - cairo=1.18.2=h3394656_1
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - coin-or-cbc=2.10.10=hd28fd6d_0
  - coin-or-cgl=0.60.9=h82e2f02_4
  - coin-or-clp=1.17.10=h8a7a1e7_1
  - coin-or-osi=0.108.11=h96cc833_4
  - coin-or-utils=2.11.12=h3a12e53_2
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=py38h06a4308_0
  - coloredlogs=15.0.1=py38h06a4308_2
  - comm=0.2.1=py38h06a4308_0
  - configargparse=1.4=pyhd3eb1b0_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - coreutils=9.5=h5eee18b_0
  - cryptography=43.0.0=py38hdda0065_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - datrie=0.8.2=py38h27cfd23_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docutils=0.18.1=py38h06a4308_3
  - dpath=2.2.0=pyha770c72_0
  - dropbox=11.36.1=py38h06a4308_0
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.0=h5888daf_0
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.4.0=py38h5eee18b_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gdbm=1.18=hd4cb3f1_4
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - gfortran_impl_linux-64=11.2.0=h7a446d4_16
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py38h06a4308_0
  - glib=2.82.2=h07242d1_1
  - glib-tools=2.82.2=h4833e2c_1
  - google-api-core=2.19.1=py38h06a4308_0
  - google-api-python-client=2.151.0=pyhff2d567_0
  - google-auth=2.29.0=py38h06a4308_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_0
  - google-cloud-core=2.3.2=py38h06a4308_0
  - google-cloud-storage=2.18.0=py38h06a4308_0
  - google-crc32c=1.5.0=py38h5eee18b_0
  - google-resumable-media=2.7.1=py38h06a4308_0
  - googleapis-common-protos=1.63.2=py38h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.62.2=py38h94a1851_0
  - gsl=2.7.1=h6e86dc7_1
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - gtftools=0.9.0=pyh5e36f6f_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - h5py=3.9.0=nompi_py38hc4a6f91_101
  - harfbuzz=10.2.0=h4bba637_0
  - hdf5=1.14.1=nompi_h4f84152_100
  - hisat2=2.2.1=h87f3376_4
  - homer=5.1=pl5262h9948957_0
  - htslib=1.22.1=h566b1c6_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - humanfriendly=10.0=py38h06a4308_1
  - icu=75.1=he02047a_0
  - idna=3.7=py38h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - jedi=0.19.1=py38h06a4308_0
  - jinja2=3.1.4=py38h06a4308_0
  - jmespath=1.0.1=py38h06a4308_0
  - joblib=1.4.2=py38h06a4308_0
  - jq=1.7.1=h5eee18b_0
  - jsonschema=4.23.0=py38h06a4308_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.1.3=h6a678d5_0
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libblas=3.9.0=20_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=20_linux64_mkl
  - libclang-cpp19.1=19.1.7=default_hb5137d0_3
  - libclang13=19.1.7=default_h9c6a7e4_3
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20191231=h46ee950_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=20_linux64_mkl
  - liblapacke=3.9.0=20_linux64_mkl
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=h043d6bf_0
  - libopenssl-static=3.5.1=hb9d3cd8_0
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2024.02.01=h2f2cdcf_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.50.1=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=257.3=h3dc2cb9_0
  - libtiff=4.7.0=hc4654cb_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.6=h024ca30_0
  - logmuse=0.2.8=pyhd8ed1ab_0
  - lz4-c=1.10.0=h5888daf_1
  - make=4.2.1=h1bed415_1
  - markdown-it-py=2.2.0=py38h06a4308_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mdurl=0.1.0=py38h06a4308_0
  - minimap2=2.28=he4a0461_3
  - mkl=2023.2.0=h84fe81f_50496
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mnnpy=0.1.9.5=py38he5da3d1_8
  - mpg123=1.32.9=hc50e24c_0
  - multidict=6.0.4=py38h5eee18b_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-connector-c=6.1.11=h659d440_1008
  - mysql-libs=9.0.1=he0572af_4
  - natsort=7.1.1=pyhd3eb1b0_0
  - nbformat=5.10.4=py38h06a4308_0
  - ncls=0.0.68=py38h0020b31_4
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=py38h06a4308_0
  - networkx=3.1=py38h06a4308_0
  - nspr=4.36=h5888daf_0
  - nss=3.112=h159eef7_0
  - numexpr=2.8.4=py38hc78ab66_1
  - numpy=1.22.3=py38hf6e8229_2
  - numpy-base=1.22.3=py38h060ed82_2
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - oniguruma=6.9.7.1=h27cfd23_0
  - openjdk=23.0.2=h68779a4_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - pandas=2.0.3=py38h1128e8f_0
  - pango=1.56.0=h861ebed_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patch=2.7.6=h7b6447c_1001
  - pcre2=10.44=hba22ea6_2
  - pephubclient=0.4.4=pyhd8ed1ab_0
  - peppy=0.40.7=pyhd8ed1ab_1
  - perl=5.34.0=h5eee18b_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h2bc05a7_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - plac=1.3.4=pyhd3eb1b0_0
  - platformdirs=3.10.0=py38h06a4308_0
  - plotly=5.24.1=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38h06a4308_0
  - prettytable=3.5.0=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - proto-plus=1.24.0=py38h06a4308_0
  - protobuf=4.25.3=py38h12ddb61_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulp=2.7.0=py38h578d9bd_1
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.6.1=py38h06a4308_0
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.8.2=py38h06a4308_0
  - pydantic-core=2.20.1=py38hb02cf49_0
  - pygments=2.15.1=py38h06a4308_1
  - pynacl=1.5.0=py38h5eee18b_0
  - pynndescent=0.5.10=py38h06a4308_0
  - pyopenssl=24.2.1=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pyranges=0.1.4=pyhdfd78af_0
  - pysftp=0.2.9=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=8.3.4=pyhd8ed1ab_0
  - python=3.8.19=hd12c33a_0_cpython
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-irodsclient=2.1.0=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.8=7_cp38
  - pytz=2024.1=py38h06a4308_0
  - pyyaml=6.0.2=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - qt-main=5.15.15=hc3cb62f_2
  - r-abind=1.4_5=r44hc72bb7e_1006
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-base=4.4.2=h64c9cd0_0
  - r-bh=1.87.0_1=r44hc72bb7e_0
  - r-bitops=1.0_9=r44h2b5f3a1_0
  - r-catools=1.18.3=r44h93ab643_0
  - r-cluster=2.1.8=r44hb67ce94_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-cpp11=0.5.1=r44hc72bb7e_0
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-curl=6.0.1=r44h2700575_0
  - r-formatr=1.14=r44hc72bb7e_2
  - r-futile.logger=1.4.3=r44hc72bb7e_1006
  - r-futile.options=1.0.1=r44hc72bb7e_1005
  - r-gplots=3.2.0=r44hc72bb7e_0
  - r-gsmoothr=0.1.7=r44hdb488b9_1007
  - r-gtools=3.9.5=r44hb1dbf0f_1
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-jsonlite=1.8.9=r44h2b5f3a1_0
  - r-kernsmooth=2.23_26=r44h8461fee_0
  - r-lambda.r=1.2.4=r44hc72bb7e_4
  - r-lattice=0.22_6=r44hb1dbf0f_1
  - r-locfit=1.5_9.10=r44h2b5f3a1_1
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.6_5=r44he966344_1
  - r-matrixstats=1.5.0=r44h2b5f3a1_0
  - r-mime=0.12=r44hb1dbf0f_3
  - r-openssl=2.2.2=r44he8289e2_0
  - r-r6=2.5.1=r44hc72bb7e_3
  - r-rcurl=1.98_1.16=r44he8228da_1
  - r-restfulr=0.0.15=r44h5ef9028_5
  - r-rjson=0.2.23=r44h93ab643_0
  - r-rsolnp=1.16=r44ha770c72_1006
  - r-snow=0.4_4=r44hc72bb7e_3
  - r-statmod=1.5.0=r44ha36c22a_2
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-truncnorm=1.0_9=r44h2b5f3a1_3
  - r-xml=3.99_0.17=r44h5bae778_2
  - r-yaml=2.3.10=r44hdb488b9_0
  - re2=2024.02.01=hdb19cb5_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py38h06a4308_0
  - requests=2.32.3=py38h06a4308_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.7.1=py38h06a4308_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.10.1=py38h06a4308_0
  - samtools=1.22.1=h96c455f_0
  - scanpy=1.9.8=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py38h1128e8f_1
  - scipy=1.8.1=py38h8ce737c_3
  - seaborn=0.13.2=py38h06a4308_0
  - sed=4.8=h7b6447c_0
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=75.1.0=py38h06a4308_0
  - setuptools-scm=8.1.0=py38h06a4308_0
  - shellingham=1.5.0=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=5.2.1=py38h06a4308_0
  - snakemake=7.32.4=hdfd78af_1
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - sorted_nearest=0.0.39=py38h0020b31_4
  - sqlite=3.31.1=h7b6447c_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stdlib-list=0.10.0=py38h06a4308_0
  - stone=3.3.1=py38h06a4308_0
  - stopit=1.1.2=py_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tabulate=0.9.0=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py38h06a4308_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h3d55465_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38h06a4308_0
  - toposort=1.10=pyhd8ed1ab_0
  - tornado=6.4.1=py38h5eee18b_0
  - tqdm=4.66.5=py38h2f386ee_0
  - traitlets=5.14.3=py38h06a4308_0
  - typer=0.9.0=py38h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - ucsc-bedgraphtobigwig=482=hdc0a859_0
  - umap-learn=0.5.4=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - unzip=6.0=h611a1e1_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wget=1.21.4=hda4d442_0
  - wheel=0.44.0=py38h06a4308_0
  - wrapt=1.14.1=py38h5eee18b_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xmltodict=0.13.0=py38h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py38h5eee18b_0
  - yq=2.12.0=pyhd3eb1b0_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.0
      - agate==1.13.0
      - agate-dbf==0.2.3
      - agate-excel==0.4.1
      - agate-sql==0.7.2
      - astunparse==1.6.3
      - babel==2.17.0
      - click==8.0.4
      - click-help-colors==0.9.4
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.1.2
      - csbdeep==0.8.1
      - csvkit==2.1.0
      - dbfread==2.0.7
      - docrep==0.3.2
      - docstring-inheritance==2.2.1
      - et-xmlfile==2.0.0
      - fiona==1.10.1
      - flatbuffers==25.2.10
      - gast==0.4.0
      - geopandas==0.13.2
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.1.1
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - inmoose==0.2.0
      - isodate==0.7.2
      - jax==0.4.13
      - jaxlib==0.4.13
      - jaxopt==0.8.5
      - jsonschema-specifications==2023.12.1
      - keras==2.13.1
      - lazy-loader==0.4
      - leather==0.4.0
      - libclang==18.1.1
      - llvmlite==0.41.1
      - markdown==3.7
      - methscan==1.1.0
      - ml-dtypes==0.2.0
      - moscot==0.3.5
      - mpmath==1.3.0
      - numba==0.58.1
      - oauthlib==3.3.0
      - olefile==0.47
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - ott-jax==0.4.6
      - packaging==24.2
      - parsedatetime==2.6
      - patsy==1.0.0
      - pip==24.3.1
      - psutil==6.1.0
      - pymetdense==1.0.1
      - pyproj==3.5.0
      - python-slugify==8.0.4
      - pytimeparse==1.1.8
      - pywavelets==1.4.1
      - requests-oauthlib==2.0.0
      - rpds-py==0.20.1
      - scikit-image==0.21.0
      - shapely==2.0.7
      - smmap==5.0.1
      - sqlalchemy==2.0.40
      - stardist==0.9.1
      - statsmodels==0.14.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - text-unidecode==1.3
      - tifffile==2023.7.10
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - xlrd==2.0.1
      - yte==1.5.4
prefix: /pasteur/appa/homes/npont/miniconda3/envs/ERC
